

if (!require("tidyverse"))install.packages("tidyverse")
if (!require("shiny"))install.packages("shiny")
if (!require("shinydashboard"))install.packages("shinydashboard")
if (!require("shinycssloaders"))install.packages("shinycssloaders")
if (!require("shinyjs"))install.packages("shinyjs")
if (!require("shinyBS"))install.packages("shinyBS")
if (!require("DT"))install.packages('DT')
if (!require("pheatmap"))install.packages('pheatmap')
if (!require("RColorBrewer"))install.packages('RColorBrewer')
if (!require("ggpubr"))install.packages('ggpubr')
if (!require("stringr"))install.packages('stringr')
if (!require("rmarkdown"))install.packages("rmarkdown")
if (!require("colourpicker"))install.packages("colourpicker")
if (!require("ggfortify"))install.packages("ggfortify")
if (!require("dendsort"))install.packages("dendsort")
if (!require("shinybusy"))install.packages("shinybusy")
if (!require("dashboardthemes"))install.packages("dashboardthemes")
if (!require("shinyWidgets"))install.packages("shinyWidgets")
if (!require("shinyvalidate"))install.packages("shinyvalidate")
if (!require("BiocManager"))install.packages('BiocManager')

if (!require("Rbowtie2"))BiocManager::install("Rbowtie2")
if (!require("Rsubread"))BiocManager::install("Rsubread")
if (!require("Rsamtools"))BiocManager::install("Rsamtools")
if (!require("clusterProfiler"))BiocManager::install("clusterProfiler")
if (!require("AnnotationHub"))BiocManager::install("AnnotationHub")
if (!require("DOSE"))BiocManager::install("DOSE")
if (!require("enrichplot"))BiocManager::install("enrichplot")
if (!require("ggridges"))install.packages('ggridges')
if (!require("ggnewscale"))install.packages('ggnewscale')
if (!require("genefilter"))BiocManager::install("genefilter")
if (!require("DESeq2"))BiocManager::install("DESeq2")
if (!require("markdown"))install.packages("markdown")
if (!require("genekitr"))install.packages("genekitr")

suppressMessages(library(shinyvalidate))
suppressMessages(library(shinyWidgets))
suppressMessages(library(shinybusy))
suppressMessages(library(genekitr))
suppressMessages(library(dashboardthemes))
suppressMessages(library(markdown))
suppressMessages(library(dendsort))
suppressMessages(library(colourpicker))
suppressMessages(library(stringr))
suppressMessages(library(genefilter))
suppressMessages(library(ggpubr))
suppressMessages(library(pheatmap))
suppressMessages(library(clusterProfiler)) 
suppressMessages(library(DOSE))
suppressMessages(library(AnnotationHub))
suppressMessages(library(enrichplot))
suppressMessages(library(shiny))
suppressMessages(library(DT))
suppressMessages(library(shinyjs))
suppressMessages(library(shinyBS))
suppressMessages(library(shinycssloaders))
suppressMessages(library(shinydashboard))
suppressMessages(library(ggplot2))
suppressMessages(library(Rsubread))
suppressMessages(library(Rbowtie2))
suppressMessages(library(DESeq2))
suppressMessages(library(tidyverse))
suppressMessages(library(ggridges)) 
suppressMessages(library(ggnewscale)) 
suppressMessages(library(RColorBrewer)) 
suppressMessages(library(rmarkdown)) 